// <auto-generated />
using System;
using Arquis.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace Arquis.Backend.Migrations
{
    [DbContext(typeof(ArquisDbContext))]
    [Migration("20261001150416_SP_OptimizarIndicesEspaciales")]
    partial class SP_OptimizarIndicesEspaciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Arquis.Backend.Models.Entities.BitacoraAcceso", b =>
                {
                    b.Property<long>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdBitacora"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("IdBitacora");

                    b.HasIndex("Fecha")
                        .IsDescending();

                    b.ToTable("BitacoraAccesos");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.BitacoraMigracion", b =>
                {
                    b.Property<long>("IdMigracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMigracion"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Capa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Exitosos")
                        .HasColumnType("int");

                    b.Property<int>("Fallidos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Omitidos")
                        .HasColumnType("int");

                    b.Property<int>("Procesados")
                        .HasColumnType("int");

                    b.Property<string>("TablaDestino")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMigracion");

                    b.ToTable("BitacoraMigraciones");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.CodigoFijo", b =>
                {
                    b.Property<int>("IdCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCodigo"));

                    b.Property<string>("CodF_SIG")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("CodF_SQL")
                        .HasColumnType("int");

                    b.Property<int?>("CodFijo")
                        .HasColumnType("int");

                    b.Property<byte>("Estado")
                        .HasColumnType("tinyint");

                    b.Property<bool>("EstadoVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCambioEstado")
                        .HasColumnType("datetime2");

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geography");

                    b.Property<int?>("IdLote")
                        .HasColumnType("int");

                    b.Property<double?>("Latitud")
                        .HasColumnType("float");

                    b.Property<double?>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdCodigo");

                    b.HasIndex("CodFijo");

                    b.HasIndex("Estado");

                    b.HasIndex("IdLote");

                    b.HasIndex("Nombre");

                    b.ToTable("CodigosFijos", t =>
                        {
                            t.HasCheckConstraint("CK_CodigosFijos_Estado", "Estado BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Lote", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geography");

                    b.Property<int?>("IdManzana")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrigen")
                        .HasColumnType("int");

                    b.Property<string>("NroLote")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdLote");

                    b.HasIndex("IdManzana");

                    b.HasIndex("NroLote");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Manzana", b =>
                {
                    b.Property<int>("IdManzana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdManzana"));

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geography");

                    b.Property<int?>("IdOrigen")
                        .HasColumnType("int");

                    b.Property<string>("MZA")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UV_MZA")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdManzana");

                    b.HasIndex("UV", "MZA");

                    b.ToTable("Manzanas");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.MenuOpcion", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdMenuPadre")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombreMenu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdMenu");

                    b.HasIndex("IdMenuPadre");

                    b.ToTable("MenuOpciones");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Iteraciones")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Usuarios_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.UsuarioMenu", b =>
                {
                    b.Property<int>("IdUsuarioMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioMenu"));

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuarioMenu");

                    b.HasIndex("IdMenu");

                    b.HasIndex("IdUsuario", "IdMenu")
                        .IsUnique();

                    b.ToTable("UsuarioMenus");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique();

                    b.ToTable("UsuariosRoles");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Via", b =>
                {
                    b.Property<int>("IdVia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVia"));

                    b.Property<Geometry>("Geom")
                        .HasColumnType("geography");

                    b.Property<string>("Nombre")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("OBJECTID")
                        .HasColumnType("int");

                    b.Property<string>("OSMID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoVia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdVia");

                    b.ToTable("Vias");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.CodigoFijo", b =>
                {
                    b.HasOne("Arquis.Backend.Models.Entities.Lote", "Lote")
                        .WithMany("CodigosFijos")
                        .HasForeignKey("IdLote");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Lote", b =>
                {
                    b.HasOne("Arquis.Backend.Models.Entities.Manzana", "Manzana")
                        .WithMany("Lotes")
                        .HasForeignKey("IdManzana");

                    b.Navigation("Manzana");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.MenuOpcion", b =>
                {
                    b.HasOne("Arquis.Backend.Models.Entities.MenuOpcion", "MenuPadre")
                        .WithMany("SubMenus")
                        .HasForeignKey("IdMenuPadre");

                    b.Navigation("MenuPadre");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.UsuarioMenu", b =>
                {
                    b.HasOne("Arquis.Backend.Models.Entities.MenuOpcion", "Menu")
                        .WithMany("UsuarioMenus")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arquis.Backend.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioMenus")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Arquis.Backend.Models.Entities.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arquis.Backend.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Lote", b =>
                {
                    b.Navigation("CodigosFijos");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Manzana", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.MenuOpcion", b =>
                {
                    b.Navigation("SubMenus");

                    b.Navigation("UsuarioMenus");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Arquis.Backend.Models.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioMenus");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
